name: abs_admin_flutter
description: Showcase App for Windows UI for Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.4.0
  provider: ^6.0.5
  system_theme: ^2.3.1
  window_manager: ^0.3.0
  flutter_acrylic: ^1.0.0+2
  url_strategy: ^0.2.0
  url_launcher: ^6.1.7
  clipboard: ^0.1.3
  email_validator: ^2.1.17
  http: ^1.1.0
  flutter_markdown: ^0.6.13
  flutter_syntax_view: 
    git:
      url: https://github.com/YehudaKremer/flutter_syntax_view.git
  go_router: ^10.0.0
  intl: ^0.18.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.1.6
  flutter_lints: ^2.0.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

